// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ansrkocqltaglvvtegkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuc3Jrb2NxbHRhZ2x2dnRlZ2t2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjc2MzIsImV4cCI6MjA1NzgwMzYzMn0.3_rG-nCn0P0uzobCem59m0XTfjz0HErl_V8JkJX-6U4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);